### ISSUE TITLE
Error with checkpoints : buffer_size must be greater than zero

### ISSUE THREAD

**Issue by RuePat** [TachibanaYoshino/AnimeGAN#60]
While trying to train the network I am getting the following error. If you could please help me figure out what might be going wrong. 

```
 [*] Reading checkpoints...
 [*] Failed to find a checkpoint
 [!] Load failed...
2022-12-03 17:46:23.362206: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at iterator_ops.cc:867 : Invalid argument: buffer_size must be greater than zero.
         [[{{node OptimizeDataset/ShuffleDataset}}]]
2022-12-03 17:46:23.373996: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at iterator_ops.cc:867 : Cancelled: Operation was cancelled
2022-12-03 17:46:23.373999: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at iterator_ops.cc:867 : Cancelled: Operation was cancelled
Traceback (most recent call last):
  File "****\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "****\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "****\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]buffer_size must be greater than zero.
         [[{{node OptimizeDataset/ShuffleDataset}}]]
         [[OneShotIterator]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 100, in <module>
    main()
  File "train.py", line 94, in main
    gan.train()
  File "****\Animeganv1\AnimeGAN-master\AnimeGAN.py", line 225, in train
    anime, anime_smooth, real = self.sess.run([anime_img_op, anime_smooth_op, real_img_op])
  File "****\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "****l\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "****\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "****\anaconda\envs\tf2\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]buffer_size must be greater than zero.
         [[{{node OptimizeDataset/ShuffleDataset}}]]
         [[OneShotIterator]]
```

**Comment by RuePat** [comment]
Data Path Issue
